# Generated by Django 4.2.30 on 2026-06-05 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('codigo_iso2', models.CharField(blank=True, default='', max_length=2)),
                ('codigo_iso3', models.CharField(blank=True, default='', max_length=3)),
                ('regiao', models.CharField(max_length=100)),
                ('sub_regiao', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Países',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilGeopolitico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(choices=[('SUP', 'Superpotência'), ('GRA', 'Grande Potência'), ('REG', 'Potência Regional'), ('MED', 'Potência Média'), ('EME', 'Potência Emergente'), ('FRA', 'Estado Frágil'), ('OUT', 'Outro')], default='OUT', max_length=3)),
                ('possui_arsenal_nuclear', models.BooleanField(default=False)),
                ('membro_conselho_seguranca', models.CharField(choices=[('P5', 'Membro Permanente (P5)'), ('ROT', 'Membro Rotativo'), ('NAO', 'Não Membro')], default='NAO', max_length=3)),
                ('gastos_militares_pct_pib', models.FloatField(blank=True, help_text='% do PIB em defesa', null=True)),
                ('indice_democracia', models.FloatField(blank=True, help_text='Economist Intelligence Unit (0-10)', null=True)),
                ('disputas_territoriais', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('pais', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='geopolitica.pais')),
            ],
            options={
                'verbose_name_plural': 'Perfis Geopolíticos',
            },
        ),
        migrations.CreateModel(
            name='BlocoInternacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(blank=True, default='', max_length=20)),
                ('tipo', models.CharField(choices=[('MIL', 'Militar'), ('ECO', 'Econômico'), ('POL', 'Político')], default='POL', max_length=3)),
                ('descricao', models.TextField(blank=True, default='')),
                ('paises', models.ManyToManyField(blank=True, related_name='blocos', to='geopolitica.pais')),
            ],
            options={
                'verbose_name_plural': 'Blocos Internacionais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('ano', models.IntegerField(default=2023)),
                ('fonte', models.CharField(default='local', max_length=100)),
                ('categoria', models.CharField(choices=[('ECO', 'Econômico'), ('POL', 'Político'), ('SOC', 'Social'), ('EST', 'Estratégico')], default='ECO', max_length=3)),
                ('codigo_api', models.CharField(blank=True, default='', max_length=50)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='geopolitica.pais')),
            ],
            options={
                'verbose_name_plural': 'Indicadores',
                'ordering': ['pais', 'tipo', '-ano'],
                'unique_together': {('pais', 'tipo', 'ano')},
            },
        ),
    ]
